name: Build Release
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14.1'

      - name: Build
        run: ./gradle build

      - name: Publish
        run: ./gradle publish -Pversion_release -Pmvn.user=${{ secrets.MAVEN_USER }} -Pmvn.key=${{ secrets.MAVEN_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/
